### ISSUE TITLE
Training time estimation

### ISSUE THREAD

**Issue by Smu-Tan** [cbaziotis/lm-prior-for-nmt#6]
Hi! I'm trying to reproduce your en-tr nmt base model, and I just found it needs **200,000 epochs** to train in `configs/transformer)/trans.entr_base.yaml`. Do you probably have any ideas about how much time will this take (only the nmt base model for en->tr)?

**Comment by cbaziotis** [comment]
Hi, it's been a long time since I run the experiments and I don't remember exactly. The dataset is very small and an epoch involves few steps. I expect that the model will converge in a few hours to a day with a modern GPU. Note that 200K epochs is the maximum number of steps. The model converges much earlier than that.
